package com.SelfServiceBarWeb.DeviceController.Message_.light;
/**
 * Title: TypeUtil.java
 * Description: this class is used to convert and reconvert a decimal number to a byte.
 * @author Jie Ji
 * @version 1.0
 */
public class TypeUtil {

    /**
     * this method is used to convert int to byte[]
     * @param num the decimal number which need be converted
     * @return the generated byte array list
     */
    public static byte[] int2Bytes(int num) {
        byte[] byteNum = new byte[4];
        for (int ix = 0; ix < 4; ++ix) {
            int offset = 32 - (ix + 1) * 8;
            byteNum[ix] = (byte) ((num >> offset) & 0xff);
        }
        return byteNum;
    }

    /**
     * byte数组中取int数值，本方法适用于(低位在后，高位在前)的顺序。
     * @param src byte array list
     * @param offset
     * @return converted decimal number
     */
    public static int bytesToInt(byte[] src, int offset) {
        int value;
        value = (int) (((src[offset] & 0xFF) << 24) | ((src[offset + 1] & 0xFF) << 16) | ((src[offset + 2] & 0xFF) << 8) | (src[offset + 3] & 0xFF));
        return value;
    }
}
